name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: [self-hosted, netcup]
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: devbox run build

      - name: Test
        run: devbox run test

      - name: Publish test report
        if: always()
        uses: dorny/test-reporter@v3.0.0
        with:
          name: Test Results
          path: build/test-results/test/*.xml
          reporter: java-junit

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests
